options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/multi-party-fhe/fhe-server', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/multi-party-fhe/fhe-server']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fhe-server'
      - '--image=gcr.io/multi-party-fhe/fhe-server'
      - '--platform=managed'
      - '--region=asia-east1'
      - '--allow-unauthenticated'
